### ISSUE TITLE
PI4B don't  boot with power suplly from leviathan board and usb connected

### ISSUE THREAD

**Issue by sergelhr** [MotorDynamicsLab/Leviathan#11]
I've got  an issue with the integrated power supply, no boot if a toolboard is connected via pi4b usb!
if a use an official 3a psu connected to the usb-c no issue pi4b boot and eveything is working (leviathan and toolboard btt sb2209)
To boot from leviathan integrated power supply i need to disconect then reconnect the usb toolboard!
weak integrated power supply?

**Comment by sergelhr** [comment]
Might be related to the 24v toolhead, feed directly from my 24v psu, what the connector type/part number of the can/24v board connector.
i don't reminder if the male connector  4 pins was provided, most probably lost!

**Comment by sergelhr** [comment]
finally is seems to be related to 24v of my toolboard, with the 24v feed from the can/24v, no boot issue , now what the max amperage available from that connector ? F3 10A?

**Comment by sergelhr** [comment]
NO; might be my raspi reaching his EOF, to be confirmed looking for an another one

**Comment by sergelhr** [comment]
look like k7805-3ar3 seems faulty, using an extenal 5v psu no more issue

**Comment by JNP-1** [comment]
The supply for the Pi delivers 3A.
The BTT SB2209 is a CAN board, have you tried to operate it via USB instead of CAN?

**Comment by JNP-1** [comment]
I have already tested Leviathan with Pi3/4/5 without any problems.
The integrated power supply for the Pi was never a problem.
However, I use CAN bus on my toolhead.
So the only difference is the interface, CAN bus instead of USB.

**Comment by sergelhr** [comment]
I don't no if  there a sort of  Power Delivery negotiation for the RPI4 USB C, my meanwell PSU is set to 5.1v and it is connected via the small pcb provided by LDO

**Comment by JNP-1** [comment]
I would not make the connection to the toolhead via USB without a protective circuit on the USB port.
Many people have already destroyed their Pi with this.
I therefore suspect that the cause lies elsewhere.

**Comment by sergelhr** [comment]
I will give a try to this product from waveshare Industrial Grade USB HUB, Extending 4x USB 2.0 Ports.
For info i ran this toolhead for a year without any issue from the usb port cm4/Manta 8p

**Comment by sergelhr** [comment]
strangely with a PI 5, from internal psu no boot issue and now all usb are passing through waveshare Industrial Grade USB HUB. My PI4b was both very old few years might be related?
